### ISSUE TITLE
获取异步报表文件 API response has not code field

### ISSUE THREAD

**Issue by waojie** [TencentAd/marketing-api-php-sdk#10]
获取异步报表文件
使用：$response = $tads->asyncReportFiles()
                             ->get([
                                 'account_id' => static::$ACCOUNT_ID,
                                 'task_id'    => static::$TASK_ID,
                                 'file_id'    => static::$FILE_ID,
                             ]);

报错：API response has not code field
原因：https://dl.e.qq.com/v1.1/async_report_files/get body返回的是" account_id....",不是json,没有code

**Comment by KylinHuang7** [comment]
这块确实有问题，我们处理下
