### ISSUE TITLE
$tads->sendBatchRequest 批量创建的时候，返回设置使用数组报错

### ISSUE THREAD

**Issue by qqzhal** [TencentAd/marketing-api-php-sdk#11]
$tads->sendBatchRequest 批量创建的时候，返回设置为数组返回报错。操作查询有成功创建

`    public function sendBatchRequest($accountId, $batchRequest)
    {
        $batchRequestSpec = $this->buildBatchRequest($accountId, $batchRequest);
        $data = $this->app->batchRequests()->add([
            'batch_request_spec' => $batchRequestSpec,
            'account_id' => $accountId,
        ]);
        $responses = $data->getList();
        $batchHandler = BatchHandler::getInstance();
        return $batchHandler->getResponses($batchRequest, $responses);
    }`

`Call to a member function getList() on array
错误位置
FILE: C:\phpStudy\domains\Spider\www\ThinkPHP\Library\Vendor\TencentAds\tencent-ad\marketing-api-php-sdk\src\TencentAds\Tools\BatchRequest.php 　LINE: 31`

**Comment by KylinHuang7** [comment]
这个问题在半个月前发布的1.1.32版已经修复了，更新一下试试呢

**Comment by qqzhal** [comment]
返回的数组值还是对象，没法纯数组么

array(2) {
  [0] => object(TencentAds\Kernel\BatchResponse)#43 (2) {
    ["e":protected] => NULL
    ["data":protected] => array(1) {
      ["campaign_id"] => int(4724556059)
    }
  }
  [1] => object(TencentAds\Kernel\BatchResponse)#42 (2) {
    ["e":protected] => NULL
    ["data":protected] => array(1) {
      ["campaign_id"] => int(4724556060)
    }
  }
}

**Comment by KylinHuang7** [comment]
嗯，这个目前还不行，这个接口比较特殊
后面我们找机会再看看能不能优化
