### ISSUE TITLE
guzzlehttp依赖问题

### ISSUE THREAD

**Issue by archdesigner** [TencentAd/marketing-api-php-sdk#3]
tencent-ad/marketing-api-php-sdk v1.1.2 requires guzzlehttp/guzzle ^6.2
目前在用7.2 guzzle

**Comment by KylinHuang7** [comment]
我们会尽快测试guzzle 7.*的兼容性，如无意外，在两周后的新版本会将版本依赖改成
guzzlehttp/guzzle ^6.2 || ^7.0 , 以兼容7.2版本
