### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by imgangge** [TencentAd/marketing-api-php-sdk#5]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in */vendor/tencent-ad/marketing-api-php-sdk/src/TencentAds/Model/TargetingTagReportsGetListStruct.php on line 1954

**Comment by KylinHuang7** [comment]
可修改php.ini中的memory_limit设置，或在运行相关代码之前调用ini_set('memory_limit', '你需要的内存大小'); 来避免内存溢出。
或者可缩小接口调用的page_size或date_range以免一次性返回太多的数据
