### ISSUE TITLE
phpdoc return type 的问题

### ISSUE THREAD

**Issue by QeeZer** [TencentAd/marketing-api-php-sdk#9]
```
/**
 * Gets accountType
 *
 * @return \TencentAds\Model\AccountType
 */
public function getAccountType()
{
    return $this->container['accountType'];
}
```

![fiNZY8.png](https://z3.ax1x.com/2021/08/03/fiNZY8.png)

![whoops.jpg](https://z3.ax1x.com/2021/08/03/fiYvvj.jpg)

上面代码注释中的 `@return \TencentAds\Model\AccountType` 表示返回的类型为该类对象，但实际返回的是 string 类型的枚举数据，在使用 PHPStan 等代码约束的工具时，整段代码全都是黄色，而且 git 限制了警告过量无法提交，所以希望贵团队将注释 `@return` 给去除，可以使用 `@returnModel`，`@returnEnum` 这种注释名替换一下，希望尽快解决一下这个问题，感谢🙏

**Comment by KylinHuang7** [comment]
好的，我们修复一下这个

**Comment by QeeZer** [comment]
👌，非常感谢，另外建议将guzzle版本的约束加一下哈，就不用手动加约束啦

**Comment by KylinHuang7** [comment]
麻烦试下v1.1.26版

**Comment by QeeZer** [comment]
点赞，返回值OK了，不过对应的参数类型的声明还是这个样子 `@param \TencentAds\Model\RoleType $roleType`

**Comment by KylinHuang7** [comment]
今天稍晚或者明天我再发一个版本修复@param

**Comment by QeeZer** [comment]
> 今天稍晚或者明天我再发一个版本修复@param

好的，非常感谢

**Comment by KylinHuang7** [comment]
v1.1.27，请试一下

**Comment by QeeZer** [comment]
> v1.1.27，请试一下

OK啦，感谢🙏
